=== VeraMaksimova/OIT/лабараторная 12 (2 XML)/note.dtd
<!DOCTYPE information [
<!ELEMENT information (univer,spes,name_of_un,ball,plan,city)>
<!ELEMENT univer (#PCDATA)>
<!ELEMENT spes (#PCDATA)>
<!ELEMENT name_of_un (#PCDATA)>
<!ELEMENT plan (#PCDATA)>
<!ELEMENT city (#PCDATA)>
]>

=== VeraMaksimova/OIT/лабараторная 12 (2 XML)/index_DTD_.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE information SYSTEM "note.dtd">
<information>
 <univer>
        <spes>ИСИТ</spes>
        <name_of_un>Белорусский национальный технический университет</name_of_un>
        <ball>Балл:322</ball>
        <plan>План набора:80</plan>
        <city>город: Минск</city>
    </univer>
<univer>
        <spes>ИСИТ</spes>
        <name_of_un>УО "Барановичский государственный университет"</name_of_un>
        <ball>Балл:282</ball>
        <plan>План набора:65</plan>
        <city>город:Барановичи</city>
</univer>
<univer>
        <spes>ИСИТ</spes>
        <name_of_un>"Белорусский государственный технологический университет"</name_of_un>
        <ball>Балл:302</ball>
        <plan>План набора:76</plan>
        <city>город:Минск</city>
</univer>
</information>
